# Site settings
title: "Développeur et consultant web & mobile - Freelance - Lausanne"
description: "Développement de site internet, application mobile (iOS/Android), application web, site e-commerce, blog. Je réalise tous vos projets sur mesure et mets mes compétences à votre service"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://adrienbigler.ch" # the base hostname & protocol for your site
name: ""

exclude: ["node_modules","readme.md"]
gems:
  - jekyll-paginate

future: false
paginate: 12
paginate_path: "/page:num/"